services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 30s
    volumes:
      - qdrant_data:/qdrant/storage

  backend:
    build: ./backend
    environment:
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-local-384}
      - LLM_PROVIDER=${LLM_PROVIDER:-stub}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OLLAMA_HOST=${OLLAMA_HOST:-http://ollama:11434}
      - VECTOR_STORE=${VECTOR_STORE:-qdrant}
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - COLLECTION_NAME=${COLLECTION_NAME:-policy_helper}
      - CHUNK_SIZE=${CHUNK_SIZE:-700}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-80}
    volumes:
      - ./data:/app/data:ro
    ports:
      - "8000:8000"
    depends_on:
      - qdrant

  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE:-http://localhost:8000}
    ports:
      - "3000:3000"

volumes:
  qdrant_data:
